### ISSUE TITLE
How to enable crypt support

### ISSUE THREAD

**Issue by bcv** [dkastner/sc#2]
Hi,

 The crypt support does not seem to work. 
 I set the CRYPT_PATH in makefile
and also used sc -x

**Comment by erithmetic** [comment]
Hi @bcv I am not an author or maintainer of sc, I am just mirroring the source here. I'm sorry, I wish I could help you!

**Comment by fauconnier** [comment]
Hello, 
This version of sc is the 7.13. The last one is 7.16 (http://ibiblio.org/pub/Linux/apps/financial/spreadsheet/sc-7.16.tar.gz). A first step could be to see if the 7.16 has the crypt support.  Also, I draw your attention to the sc-im project (https://github.com/andmarti1424/sc-im) which aims at modernizing sc.

**Comment by fauconnier** [comment]
I updated the repo to sc 7.16.
@bcv could you please try again for the crypt support?
